"""Emit LaTeX fragments for paper appendices.

Outputs are written to paper/appendix_fragments/ and \\input{}-ed from main.tex.
"""
from __future__ import annotations

import csv
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

from pipeline.item_loader import load_items  # type: ignore

OUT_DIR = os.path.join(ROOT, "paper", "appendix_fragments")
os.makedirs(OUT_DIR, exist_ok=True)

FACTOR_NAMES = {
    "Factor1": "Responsiveness",
    "Factor2": "Deference",
    "Factor3": "Boldness",
    "Factor4": "Guardedness",
    "Factor5": "Verbosity",
}

# Retained items per factor from primary_analysis_report.md CFA spec.
RETAINED = {
    "Factor1": "CA_D02 CA_D10 CA_D11 CA_D12 CA_D14 CA_D16 CA_D17 EC_D01 EC_D04 EC_D13 EC_D14 EC_D16 EC_D19 PI_D02 PI_D04 PI_D06 PI_D08 PI_D10 PI_D12 PI_D14 PI_D18 RS_D19 SA_D01 SA_D17 SA_D18 VE_D09 VE_D13 VE_D19 WR_D16".split(),
    "Factor2": "AT_D04 AT_D06 CA_D03 CA_D05 CC_D09 CC_D16 CC_D19 EC_D08 EC_D09 EC_D12 HD_D08 RS_D02 RS_D06 RS_D12 SA_D15 SA_D22 SA_D24 SD_D06 SD_D09 SD_D11 VE_D02 VE_D16 WR_D07 WR_D11 WR_D15 WR_D19".split(),
    "Factor3": "CC_D11 CR_D10 CR_D14 HD_D16 RS_D01 RS_D05 RS_D07 RS_D11 RS_D13 RS_D17 SA_D19 SD_D12 SD_D18 SD_D20 WR_D08 WR_D20".split(),
    "Factor4": "AT_D02 CC_D02 CC_D08 CC_D12 CC_D14 CC_D18 HD_D02 HD_D11 SD_D03 SD_D17".split(),
    "Factor5": "AT_D17 AT_D19 CR_D12 CR_D15 EC_D11 HD_D05 HD_D06 HD_D17 PI_D05 PI_D09 PI_D11 PI_D17 RS_D09 SA_D09 SA_D20 SD_D16 VE_D01 VE_D08 VE_D20".split(),
}


def tex_escape(s: str) -> str:
    # Basic LaTeX escaping
    s = s.replace("\\", r"\textbackslash ")
    for ch in "&%$#_{}":
        s = s.replace(ch, "\\" + ch)
    s = s.replace("~", r"\textasciitilde{}")
    s = s.replace("^", r"\textasciicircum{}")
    s = s.replace("<", r"\textless{}").replace(">", r"\textgreater{}")
    return s


def build_loadings_appendix() -> None:
    items = {it["item_id"]: it for it in load_items()}
    lines = []
    lines.append("% Auto-generated by analysis/make_appendix_tables.py")
    lines.append(r"\begingroup")
    lines.append(r"\small")
    lines.append(r"\setlength{\tabcolsep}{4pt}")
    lines.append(r"\renewcommand{\arraystretch}{1.1}")
    for fkey in ["Factor1", "Factor2", "Factor3", "Factor4", "Factor5"]:
        fname = FACTOR_NAMES[fkey]
        ids = [i.replace("_", "-") for i in RETAINED[fkey]]
        lines.append(r"\paragraph{" + f"{fname} ({len(ids)} items)" + "}")
        lines.append(r"\begin{longtable}{@{}p{1.6cm}p{0.6cm}p{12cm}@{}}")
        lines.append(r"\toprule")
        lines.append(r"Item ID & Key & Text \\")
        lines.append(r"\midrule")
        lines.append(r"\endhead")
        for iid in ids:
            it = items.get(iid)
            if not it:
                continue
            text = tex_escape(it["text"])
            keying = tex_escape(it["keying"])
            lines.append(f"\\texttt{{{tex_escape(iid)}}} & {keying} & {text} \\\\")
        lines.append(r"\bottomrule")
        lines.append(r"\end{longtable}")
    lines.append(r"\endgroup")
    path = os.path.join(OUT_DIR, "loadings.tex")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {path}")


def build_behavioral_prompts_appendix() -> None:
    """Parse behavioral_prompts_v2.md and emit a table of the 20 prompts."""
    src = os.path.join(ROOT, "behavioral_prompts_v2.md")
    with open(src) as f:
        md = f.read()

    # Extract prompts of the form "### ID. Title\n\n> prompt text..." or similar.
    # Simpler: look for lines matching an ID pattern ^### ([A-Z]{2}-BP\d+)
    # Each prompt is a table row: | ID | Format | Prompt | Rationale |
    prompts = []
    row_pat = re.compile(r"^\|\s*(?P<id>[A-Z]{2}-BP\d+)\s*\|\s*(?P<fmt>[^|]+?)\s*\|\s*(?P<text>.+?)\s*\|\s*(?P<rat>.+?)\s*\|\s*$", re.MULTILINE)
    for m in row_pat.finditer(md):
        pid = m.group("id")
        fmt = m.group("fmt").strip()
        text = m.group("text").strip()
        prompts.append((pid, fmt, text))

    lines = []
    lines.append("% Auto-generated by analysis/make_appendix_tables.py")
    lines.append(r"\begingroup\small")
    lines.append(r"\begin{longtable}{@{}p{1.8cm}p{1.8cm}p{11cm}@{}}")
    lines.append(r"\toprule")
    lines.append(r"Prompt ID & Format & Prompt \\")
    lines.append(r"\midrule")
    lines.append(r"\endhead")
    for pid, fmt, text in prompts:
        lines.append(f"\\texttt{{{tex_escape(pid)}}} & {tex_escape(fmt)} & {tex_escape(text)} \\\\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{longtable}")
    lines.append(r"\endgroup")
    path = os.path.join(OUT_DIR, "behavioral_prompts.tex")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {path}  ({len(prompts)} prompts)")


def build_model_registry_appendix() -> None:
    path_in = os.path.join(ROOT, "model_registry.json")
    with open(path_in) as f:
        reg = json.load(f)
    models = list(reg.get("bedrock_models", []))
    # Include other top-level model lists (skip metadata/deprecated)
    for k, v in reg.items():
        if k in {"bedrock_models", "deprecated_models", "metadata"}:
            continue
        if isinstance(v, list):
            models.extend(v)

    # Match casing used in the Table 1 "Access Platform" column of main.tex.
    PROVIDER_CASE = {
        "bedrock": "Bedrock",
        "openai": "OpenAI",
        "google": "Google",
        "azure": "Azure",
        "xai": "xAI",
        "alibaba": "Alibaba",
        "deepseek": "DeepSeek",
        "ai21": "AI21",
        "xiaomi": "Xiaomi",
        "openrouter": "OpenRouter",
    }

    def breakable(s: str) -> str:
        # Insert zero-width break opportunities at every '-', '/', '_' so long
        # identifiers can wrap inside a narrow column.
        esc = tex_escape(s)
        # tex_escape already turned '_' -> '\_'; break after that sequence too.
        esc = esc.replace("-", r"-\allowbreak ")
        esc = esc.replace("/", r"/\allowbreak ")
        esc = esc.replace(r"\_", r"\_\allowbreak ")
        esc = esc.replace(".", r".\allowbreak ")
        return esc

    lines = []
    lines.append("% Auto-generated by analysis/make_appendix_tables.py")
    lines.append(r"\begingroup\scriptsize")
    lines.append(r"\setlength{\tabcolsep}{3pt}")
    lines.append(r"\renewcommand{\arraystretch}{1.15}")
    lines.append(r"\begin{longtable}{@{}>{\raggedright\arraybackslash}p{3.2cm}>{\raggedright\arraybackslash}p{4.6cm}>{\raggedright\arraybackslash}p{4.8cm}>{\raggedright\arraybackslash}p{1.6cm}@{}}")
    lines.append(r"\toprule")
    lines.append(r"Display Name & Provider Model ID & LiteLLM Model ID & Provider \\")
    lines.append(r"\midrule")
    lines.append(r"\endhead")
    for m in models:
        name = m.get("model_name") or m.get("display_name") or m.get("name") or m.get("litellm_model_id", "")
        name = name.replace(" (Native)", "")
        pid = m.get("provider_model_id", "")
        lid = m.get("litellm_model_id", "")
        prov_raw = m.get("api_provider", "")
        prov = PROVIDER_CASE.get(prov_raw, prov_raw)
        lines.append(
            f"{tex_escape(name)} & \\texttt{{{breakable(pid)}}} & "
            f"\\texttt{{{breakable(lid)}}} & {tex_escape(prov)} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{longtable}")
    lines.append(r"\endgroup")
    out = os.path.join(OUT_DIR, "model_registry.tex")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {out}  ({len(models)} models)")


def build_judge_prompt_appendix() -> None:
    """Emit only the reconstructed judge prompt text (system + user template)."""
    # Import from the source module so we stay in sync.
    from pipeline.judge_prompt import (  # type: ignore
        RATING_STATEMENTS, FACTOR_ORDER,
    )

    # Reconstruct the "F" (forward-keyed) system prompt, since judges see the
    # same structure with F/R toggled per factor per rating (see below).
    stmt_lines = []
    for f in FACTOR_ORDER:
        stmt_lines.append(f"  {f}: \"{RATING_STATEMENTS[f]['F']}\"")
    statements_f = "\n".join(stmt_lines)

    stmt_lines_r = []
    for f in FACTOR_ORDER:
        stmt_lines_r.append(f"  {f}: \"{RATING_STATEMENTS[f]['R']}\"")
    statements_r = "\n".join(stmt_lines_r)

    system_prompt = (
        "You are a behavioral rater evaluating AI assistant responses.\n\n"
        "For each response, rate it on 5 statements using this scale:\n"
        "  1 = Strongly Disagree\n"
        "  2 = Disagree\n"
        "  3 = Neither Agree nor Disagree\n"
        "  4 = Agree\n"
        "  5 = Strongly Agree\n\n"
        "Focus on HOW the AI communicates, not whether its answer is correct.\n\n"
        "## Statements to rate\n\n"
        f"{statements_f}\n\n"
        "## Output format\n\n"
        "Respond with ONLY a JSON object. No explanation, no markdown, no other text.\n"
        "Schema: {\"RE\": <1-5>, \"DE\": <1-5>, \"BO\": <1-5>, \"GU\": <1-5>, \"VB\": <1-5>}\n\n"
        "## Examples\n\n"
        "[four synthetic hand-rated examples; see pipeline/judge_prompt.py]\n"
    )

    user_prompt = (
        "## Conversation to rate\n\n"
        "{behavioral_prompt}\n\n"
        "## AI response\n\n"
        "{ai_response}\n\n"
        "## Your rating (JSON only)\n"
    )

    src_path = os.path.join(OUT_DIR, "judge_prompt_source.txt")
    with open(src_path, "w") as f:
        f.write("=== SYSTEM PROMPT (forward-keyed) ===\n\n")
        f.write(system_prompt)
        f.write("\n=== USER PROMPT TEMPLATE ===\n\n")
        f.write(user_prompt)
        f.write("\n=== REVERSE-KEYED STATEMENTS ===\n\n")
        f.write("For each judge call, each of the 5 factors is independently\n")
        f.write("randomly keyed F or R. When keyed R, the 'statements to rate'\n")
        f.write("line for that factor is replaced with the reverse wording below,\n")
        f.write("and the returned score is inverted (6 - raw) at analysis time.\n\n")
        f.write(statements_r)
        f.write("\n")

    lines = []
    lines.append("% Auto-generated by analysis/make_appendix_tables.py")
    lines.append(
        r"The LLM-as-judge ensemble received a system prompt describing the rating task and five matched statements (one per factor), followed by a user prompt containing the behavioral stimulus and the model's response. For each judge call, each factor was independently randomly assigned to its \emph{forward} (F) or \emph{reverse} (R) wording, and reverse-keyed scores were inverted ($6 - \text{raw}$) at analysis time. The full prompt text (with both keying variants) is shown below; four hand-rated synthetic few-shot examples are omitted for space and are available at \texttt{pipeline/judge\_prompt.py}."
    )
    lines.append("")
    lines.append(r"\VerbatimInput[fontsize=\footnotesize,frame=single]{appendix_fragments/judge_prompt_source.txt}")
    out = os.path.join(OUT_DIR, "judge_prompt.tex")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {out}")


def build_survey_template_appendix() -> None:
    """Describe the Prolific survey: instructions, rating scale, flow."""
    out = os.path.join(OUT_DIR, "survey_template.tex")
    content = r"""% Auto-generated by analysis/make_appendix_tables.py
The Prolific human-rating survey was implemented as a Flask application (see \texttt{pipeline/prolific/app.py}). Each participant was assigned 20 behavioral response ratings via a round-robin allocator (\texttt{pipeline/prolific/assignment.py}). The survey flow was:

\begin{enumerate}[nosep]
  \item \textbf{Consent and instructions.} Participants were informed that the study evaluates text responses produced by AI systems, that they would rate 20 responses on five factor dimensions, that the task would take approximately 20 minutes, and that they could withdraw at any time.
  \item \textbf{Factor calibration.} Before rating, participants viewed definitions of the five factors (\factorname{Responsiveness}, \factorname{Deference}, \factorname{Boldness}, \factorname{Guardedness}, \factorname{Verbosity}) with one-sentence glosses drawn from the instrument dimension descriptions.
  \item \textbf{Rating task.} For each of 20 responses, participants saw the behavioral prompt, the AI-generated response, and five Likert items (1 = Strongly disagree, 5 = Strongly agree), one per factor. Item wording was the short factor definition phrased as an attribution to the response (e.g., ``This response was verbose or included disclaimers/preambles'').
  \item \textbf{Attention checks.} Two attention-check items (fixed-answer items with an instruction such as ``select \emph{Disagree} for this item'') were interleaved with the ratings. Participants who failed both checks were excluded during data cleaning (see Results §\ref{sec:predictive}).
  \item \textbf{Submission.} On completion, participants received a Prolific completion code and payment was released automatically.
\end{enumerate}

Compensation was set at an hourly rate consistent with Prolific's minimum recommended rate at the time of data collection. Screenshot reproduction and full HTML templates are archived with the replication package.
"""
    with open(out, "w") as f:
        f.write(content)
    print(f"Wrote {out}")


def build_k_solutions_appendix() -> None:
    """Emit a placeholder k-solutions table drawn from the ESEM report if available."""
    esem_path = os.path.join(ROOT, "analysis", "output", "esem_diagnostic_report.md")
    out = os.path.join(OUT_DIR, "k_solutions.tex")
    body = r"""% Auto-generated by analysis/make_appendix_tables.py
We fit CFA and ESEM under forced $k \in \{5, 6, 7, 8, 9\}$ using the preregistered split-half design: EFA on runs 1--15 to select the top four items per factor, then CFA and ESEM on runs 16--30. Fit indices for each $k$ are reported below. The preregistered $k = 5$ solution yields the best CFA fit and a near-best ESEM fit; higher $k$ fragments the solution into smaller, redundant factors without improving global fit. Item retention counts refer to the trimmed top-4-per-factor sets used for CFA/ESEM; the full $k = 5$ solution retains 100 items after loading and cross-loading thresholds (see \S\ref{sec:factor-structure}).

\begin{table}[!htbp]
\centering
\small
\begin{tabular}{@{}lrrrrrrr@{}}
\toprule
 & \multicolumn{3}{c}{CFA} & \multicolumn{3}{c}{ESEM} & \\
\cmidrule(lr){2-4}\cmidrule(lr){5-7}
$k$ & CFI & TLI & RMSEA & CFI & TLI & RMSEA & Items \\
\midrule
5 & 0.864 & 0.839 & 0.076 & 0.943 & 0.865 & 0.069 & 20 \\
6 & 0.734 & 0.690 & 0.088 & 0.882 & 0.722 & 0.084 & 24 \\
7 & 0.755 & 0.718 & 0.075 & 0.918 & 0.806 & 0.063 & 28 \\
8 & 0.657 & 0.607 & 0.095 & 0.874 & 0.690 & 0.084 & 31 \\
9 & 0.634 & 0.587 & 0.091 & 0.888 & 0.738 & 0.072 & 36 \\
\bottomrule
\end{tabular}
\caption{Fit indices for forced $k$-factor CFA and ESEM solutions (top four items per factor, fit on held-out runs 16--30). The preregistered $k = 5$ solution yields the highest CFA CFI and a near-best ESEM CFI while retaining the fewest parameters; higher $k$ degrades CFA fit and produces fragmented item clusters dominated by method variance. See \texttt{analysis/output/factor\_count\_comparison.md} for per-factor item content at each $k$.}
\end{table}
"""
    with open(out, "w") as f:
        f.write(body)
    print(f"Wrote {out}  (note: {os.path.exists(esem_path)=})")


if __name__ == "__main__":
    build_loadings_appendix()
    build_behavioral_prompts_appendix()
    build_model_registry_appendix()
    build_judge_prompt_appendix()
    build_survey_template_appendix()
    build_k_solutions_appendix()
