"""Section 5: Assemble the diagnostic markdown report from all section outputs."""

from pathlib import Path

import numpy as np
import pandas as pd


def df_to_markdown(df: pd.DataFrame, max_rows: int = 100, float_fmt: str = ".3f") -> str:
    """Convert a DataFrame to a markdown table string."""
    if len(df) > max_rows:
        df = df.head(max_rows)

    # Format floats
    formatted = df.copy()
    for col in formatted.select_dtypes(include=["float64", "float32"]).columns:
        formatted[col] = formatted[col].apply(
            lambda x: f"{x:{float_fmt}}" if pd.notna(x) else ""
        )

    return formatted.to_markdown(index=False)


def flagged_items_table(
    item_variance: pd.DataFrame,
    item_refusals: pd.DataFrame,
    item_total_r: pd.DataFrame,
    loading_report: pd.DataFrame | None = None,
) -> pd.DataFrame:
    """Merge all item-level flags into a single table.

    Returns DataFrame with: item_id, dimension, flag_reasons.
    """
    flags = {}

    # Zero-variance candidates
    zv = item_variance[item_variance["flagged_zero_var"]]
    for _, row in zv.iterrows():
        key = row["item_id"]
        flags.setdefault(key, {"dimension": row["dimension"], "reasons": []})
        flags[key]["reasons"].append(
            f"zero-var (range={row['range_of_means']:.2f})"
        )

    # High refusal items
    hr = item_refusals[item_refusals["flagged_refusal"]]
    for _, row in hr.iterrows():
        key = row["item_id"]
        flags.setdefault(key, {"dimension": "", "reasons": []})
        flags[key]["reasons"].append(
            f"high refusal ({row['refusal_rate']:.1%})"
        )

    # Low item-total r
    if len(item_total_r) > 0:
        lr = item_total_r[item_total_r["flagged_low_r"] == True]
        for _, row in lr.iterrows():
            key = row["item_id"]
            dim = row.get("dimension", "")
            flags.setdefault(key, {"dimension": dim, "reasons": []})
            if dim:
                flags[key]["dimension"] = dim
            r_val = row["item_total_r"]
            r_str = f"{r_val:.2f}" if pd.notna(r_val) else "NaN"
            flags[key]["reasons"].append(f"low item-total r={r_str}")

    # Wrong-factor loading
    if loading_report is not None and len(loading_report) > 0:
        flagged_loadings = loading_report[loading_report["flag"] != ""]
        for _, row in flagged_loadings.iterrows():
            key = row["item_id"]
            dim = row.get("dimension", "")
            flags.setdefault(key, {"dimension": dim, "reasons": []})
            if dim:
                flags[key]["dimension"] = dim
            flags[key]["reasons"].append(f"EFA: {row['flag']}")

    if not flags:
        return pd.DataFrame(columns=["item_id", "dimension", "flag_reasons"])

    rows = [
        {"item_id": k, "dimension": v["dimension"], "flag_reasons": "; ".join(v["reasons"])}
        for k, v in sorted(flags.items())
    ]
    return pd.DataFrame(rows)


def flagged_models_table(flagged_models: pd.DataFrame) -> pd.DataFrame:
    """Format flagged models for the report."""
    if len(flagged_models) == 0:
        return pd.DataFrame(columns=["short_name", "model_id", "flag_reason"])
    return flagged_models[["short_name", "model_id", "total", "success_rate",
                           "refusal_rate", "parse_error_rate", "flag_reason"]].copy()


def _relative_plot_path(abs_path: str, report_dir: str) -> str:
    """Convert absolute plot path to relative from report directory."""
    return str(Path(abs_path).relative_to(Path(report_dir)))


def generate_report(
    engineering: dict,
    item_quality: dict,
    dimension_coherence: dict,
    factor_structure: dict | None,
    output_path: str,
) -> None:
    """Write the full diagnostic_report.md."""
    report_dir = str(Path(output_path).parent)
    lines = []
    lines.append("# Preliminary Diagnostic Report")
    lines.append("")
    lines.append("*Auto-generated by `python -m analysis.run_diagnostics`*")
    lines.append("")

    # ---- Section 1: Engineering Checks ----
    lines.append("## 1. Engineering Checks")
    lines.append("")
    lines.append("### Per-Model Summary")
    lines.append("")
    summary = engineering["model_summary"]
    display_cols = [
        "short_name", "total", "success", "parse_error", "api_error",
        "refusal", "success_rate", "refusal_rate", "parse_error_rate",
        "primary_scoring_method", "n_items", "n_runs",
    ]
    lines.append(df_to_markdown(summary[display_cols]))
    lines.append("")

    if len(engineering["flagged_models"]) > 0:
        lines.append("### Flagged Models")
        lines.append("")
        lines.append(df_to_markdown(flagged_models_table(engineering["flagged_models"])))
        lines.append("")
    else:
        lines.append("### Flagged Models")
        lines.append("")
        lines.append("No models flagged (all refusal rates ≤25%, parse error rates ≤5%).")
        lines.append("")

    oor = engineering["out_of_range"]
    if len(oor) > 0:
        lines.append("### Out-of-Range Scores")
        lines.append("")
        lines.append(f"**{len(oor)} out-of-range scores found:**")
        lines.append("")
        lines.append(df_to_markdown(oor.head(20)))
        lines.append("")
    else:
        lines.append("### Out-of-Range Scores")
        lines.append("")
        lines.append("All scores within expected ranges (direct: 1-5, scenario: 1-4).")
        lines.append("")

    # ---- Section 2: Item-Level Quality ----
    lines.append("## 2. Item-Level Quality")
    lines.append("")

    lines.append("### Item Variance Across Models")
    lines.append("")
    variance = item_quality["item_variance"]
    n_zv = variance["flagged_zero_var"].sum()
    lines.append(f"**{n_zv} items flagged** as zero-variance candidates (range of model means < 0.5).")
    lines.append("")
    if n_zv > 0:
        zv_items = variance[variance["flagged_zero_var"]].sort_values("range_of_means")
        lines.append(df_to_markdown(
            zv_items[["item_id", "dimension", "item_type", "mean_of_means", "std_of_means",
                       "range_of_means", "n_models"]]
        ))
        lines.append("")

    lines.append("### Item Refusal Rates")
    lines.append("")
    refusals = item_quality["item_refusals"]
    n_hr = refusals["flagged_refusal"].sum()
    lines.append(f"**{n_hr} items flagged** with refusal rate >10%.")
    lines.append("")
    if n_hr > 0:
        lines.append(df_to_markdown(
            refusals[refusals["flagged_refusal"]].sort_values("refusal_rate", ascending=False)
        ))
        lines.append("")

    lines.append("### Item-Total Correlations")
    lines.append("")
    itr = item_quality["item_total_r"]
    if len(itr) > 0:
        n_low = itr["flagged_low_r"].sum()
        lines.append(f"**{n_low} items flagged** with corrected item-total r < 0.30.")
        lines.append("")
        # Infer N from the score matrix that was used
        n_models = itr["item_total_r"].notna().sum() // max(len(itr), 1) or "?"
        lines.append(f"**Note:** Item-total correlations are computed within candidate dimensions at the model level. Since EFA discovers cross-dimensional factors, low within-dimension item-total r does not necessarily indicate a poor item.")
        lines.append("")
        if n_low > 0:
            low_r = itr[itr["flagged_low_r"]].sort_values("item_total_r")
            lines.append(df_to_markdown(
                low_r[["item_id", "dimension", "item_type", "item_total_r"]]
            ))
            lines.append("")

        # Summary by dimension
        dim_summary = (
            itr.groupby(["dimension", "item_type"])["item_total_r"]
            .agg(["mean", "min", "count"])
            .reset_index()
        )
        dim_summary.columns = ["dimension", "item_type", "mean_r", "min_r", "n_items"]
        lines.append("**Item-total r summary by dimension:**")
        lines.append("")
        lines.append(df_to_markdown(dim_summary))
        lines.append("")

    # ---- Section 3: Dimension-Level Coherence ----
    lines.append("## 3. Dimension-Level Coherence")
    lines.append("")

    lines.append("### Reliability (Direct Items)")
    lines.append("")
    rel_direct = dimension_coherence["reliability_direct"]
    lines.append(df_to_markdown(rel_direct))
    lines.append("")
    n_low_alpha = rel_direct["flagged_low_alpha"].sum()
    if n_low_alpha > 0:
        flagged_dims = rel_direct[rel_direct["flagged_low_alpha"]]["dimension"].tolist()
        lines.append(f"**{n_low_alpha} dimensions flagged** with alpha < 0.60: {', '.join(flagged_dims)}")
        lines.append("")

    rel_scenario = dimension_coherence.get("reliability_scenario")
    if rel_scenario is not None and len(rel_scenario) > 0:
        lines.append("### Reliability (Scenario Items)")
        lines.append("")
        lines.append(df_to_markdown(rel_scenario))
        lines.append("")

    lines.append("### Inter-Item Correlation Heatmaps")
    lines.append("")
    for path in dimension_coherence.get("plot_paths", []):
        rel_path = _relative_plot_path(path, report_dir)
        dim_name = Path(path).stem.replace("heatmap_", "").replace("_", " ")
        lines.append(f"#### {dim_name}")
        lines.append(f"![{dim_name}]({rel_path})")
        lines.append("")

    # ---- Section 4: Factor Structure ----
    if factor_structure is not None:
        lines.append("## 4. Preliminary Factor Structure")
        lines.append("")

        shape = factor_structure.get("pooled_shape", (0, 0))
        n_models = factor_structure.get("n_models", 0)
        lines.append(f"Pooled matrix: **{shape[0]} observations × {shape[1]} items** from {n_models} models.")
        lines.append("")

        # ICC
        icc_df = factor_structure.get("icc")
        if icc_df is not None:
            valid_icc = icc_df["icc"].dropna()
            lines.append("### ICC Analysis")
            lines.append("")
            lines.append(f"- Median ICC(1): **{valid_icc.median():.3f}**")
            lines.append(f"- Mean ICC(1): **{valid_icc.mean():.3f}**")
            lines.append(f"- Items with ICC > 0.60 (good+): **{(valid_icc > 0.60).sum()}/{len(valid_icc)}**")
            lines.append(f"- Items with ICC < 0.40 (poor): **{(valid_icc < 0.40).sum()}/{len(valid_icc)}**")
            lines.append("")

            icc_plot = factor_structure.get("icc_plot")
            if icc_plot:
                lines.append(f"![ICC distribution]({_relative_plot_path(icc_plot, report_dir)})")
                lines.append("")

        # Parallel analysis
        pa = factor_structure.get("parallel_analysis")
        if pa:
            lines.append("### Parallel Analysis")
            lines.append("")
            lines.append(f"Suggested number of factors: **{pa['n_factors_suggested']}**")
            lines.append("")
            scree = factor_structure.get("scree_plot")
            if scree:
                lines.append(f"![Scree plot]({_relative_plot_path(scree, report_dir)})")
                lines.append("")

        # EFA results
        efa = factor_structure.get("efa")
        if efa and "error" not in efa:
            lines.append("### EFA Results")
            lines.append("")
            lines.append(f"Method: **{efa['method_used']}** with oblimin rotation")
            lines.append("")

            loadings_plot = factor_structure.get("loadings_plot")
            if loadings_plot:
                lines.append(f"![Factor loadings]({_relative_plot_path(loadings_plot, report_dir)})")
                lines.append("")

            # Factor correlation matrix
            fc = efa.get("factor_correlation")
            if fc is not None:
                lines.append("**Factor correlation matrix:**")
                lines.append("")
                lines.append(df_to_markdown(fc.reset_index()))
                lines.append("")

            # Loading report summary
            lr = factor_structure.get("loading_report")
            if lr is not None:
                n_flagged = (lr["flag"] != "").sum()
                lines.append(f"**{n_flagged}/{len(lr)} items flagged** (low primary loading or cross-loading)")
                lines.append("")

                # Dimension → primary factor mapping
                dim_factor = (
                    lr.groupby("dimension")["primary_factor"]
                    .agg(lambda x: x.value_counts().index[0])
                    .reset_index()
                )
                dim_factor.columns = ["dimension", "modal_primary_factor"]
                lines.append("**Dimension → modal primary factor mapping:**")
                lines.append("")
                lines.append(df_to_markdown(dim_factor))
                lines.append("")

        elif efa and "error" in efa:
            lines.append("### EFA Results")
            lines.append("")
            lines.append(f"**EFA failed:** {efa['error']}")
            lines.append("")

    # ---- Section 5: Summary ----
    lines.append("## 5. Summary")
    lines.append("")

    # Flagged items
    loading_report_df = None
    if factor_structure and "loading_report" in factor_structure:
        loading_report_df = factor_structure["loading_report"]

    flagged = flagged_items_table(
        item_quality["item_variance"],
        item_quality["item_refusals"],
        item_quality["item_total_r"],
        loading_report_df,
    )
    lines.append("### Flagged Items")
    lines.append("")
    lines.append(f"**{len(flagged)} items flagged** across all checks.")
    lines.append("")
    if len(flagged) > 0:
        lines.append(df_to_markdown(flagged))
        lines.append("")

    # Flagged models
    lines.append("### Flagged Models")
    lines.append("")
    fm = engineering["flagged_models"]
    if len(fm) > 0:
        lines.append(f"**{len(fm)} models flagged:**")
        lines.append("")
        lines.append(df_to_markdown(flagged_models_table(fm)))
    else:
        lines.append("No models flagged.")
    lines.append("")

    # Write
    Path(output_path).write_text("\n".join(lines))
    print(f"Report written to {output_path}")
